keys:
  - &host_wassaa age1fkmzf05vfxfzuedgwsq9paf4ldqw34ud4zc88u6amjpqv47wrsashx0a6k
  - &user_wassaa age1mnzfczftwm3vkdtsh8ds0jlt7xv7p805zq8ukhwehg65vnfnqe6qpte2p8
  - &host_tpad age18krrdn63ezwvcn2n9nt4tdwxkw4s5qqdfjrtu54raych3rmpfvxsnnpcax
  - &user_tpad age10lc9chrd47r3sdmqwj604x5gtdxkx6n0deffqxnyf9g30w0kuvxqm9h345


creation_rules:
  - path_regex: hosts/wassaa/secrets.ya?ml$
    key_groups:
    - age:
      - *host_wassaa
      - *user_wassaa
  - path_regex: hosts/tpad/secrets.ya?ml$
    key_groups:
    - age:
      - *host_tpad
      - *user_tpad

